app = 'findmy-webapp'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile.webapp"

[env]
  MIDDLEWARE_URL = "http://findmy-middleware-dappled-silence-7211.internal:5500"
  GRAFANA_INTERNAL_URL = "http://findmy-grafana.internal:3000"

[[services]]
  protocol      = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port     = 80
    handlers = ['http']

  [[services.ports]]
    port     = 443
    handlers = ['tls', 'http']

  [[services.http_checks]]
    interval     = '30s'
    timeout      = '5s'
    grace_period = '10s'
    method       = 'GET'
    path         = '/login'

[[vm]]
  memory   = '256mb'
  cpu_kind = 'shared'
  cpus     = 1
